#!/usr/bin/env bash
set -e
[ -n "$GOVENV_DEBUG" ] && set -x

# Provide govenv completions
if [ "$1" = "--complete" ]; then
  exec govenv-rehash --complete
fi

shell="$(basename "${GOVENV_SHELL:-$SHELL}")"

# When govenv shell integration is enabled,
# delegate to govenv-rehash,
# then tell the shell to empty its command lookup cache.
govenv-rehash

case "$shell" in
fish )
  # no rehash support
  ;;
* )
  echo "hash -r 2>/dev/null || true"
  ;;
esac
