#!/usr/bin/env bash
# Summary: Show the current Go version and its origin
#
# Shows the currently selected Go version and how it was
# selected. To obtain only the version string, use `govenv
# version-name'.

set -e
[ -n "$GOVENV_DEBUG" ] && set -x

exitcode=0
OLDIFS="$IFS"
IFS=: GOVENV_VERSION_NAMES=($(govenv-version-name)) || exitcode=$?
IFS="$OLDIFS"

for GOVENV_VERSION_NAME in "${GOVENV_VERSION_NAMES[@]}"; do
  echo "$GOVENV_VERSION_NAME (set by $(govenv-version-origin))"
done

exit $exitcode
