#!/usr/bin/env bash
# Summary: Explain how the current Go version is set
set -e
[ -n "$GOVENV_DEBUG" ] && set -x

unset GOVENV_VERSION_ORIGIN

OLDIFS="$IFS"
IFS=$'\n' scripts=(`govenv-hooks version-origin`)
IFS="$OLDIFS"
for script in "${scripts[@]}"; do
  source "$script"
done

if [ -n "$GOVENV_VERSION_ORIGIN" ]; then
  echo "$GOVENV_VERSION_ORIGIN"
elif [ -n "$GOVENV_VERSION" ]; then
  echo "GOVENV_VERSION environment variable"
else
  govenv-version-file
fi
