#!/usr/bin/env bash
set -e
export -n CDPATH

if [ "$1" = "--debug" ]; then
  export GOVENV_DEBUG=1
  shift
fi

if [ -n "$GOVENV_DEBUG" ]; then
  export PS4='+ [${BASH_SOURCE##*/}:${LINENO}] '
  set -x
fi

abort() {
  { if [ "$#" -eq 0 ]; then cat -
    else echo "govenv: $*"
    fi
  } >&2
  exit 1
}

if enable -f "${BASH_SOURCE%/*}"/../libexec/govenv-realpath.dylib realpath 2>/dev/null; then
  abs_dirname() {
    local path="$(realpath "$1")"
    echo "${path%/*}"
  }
else
  [ -z "$GOVENV_NATIVE_EXT" ] || abort "failed to load \`realpath' builtin"

  READLINK=$(type -p greadlink readlink | head -1)
  [ -n "$READLINK" ] || abort "cannot find readlink - are you missing GNU coreutils?"

  resolve_link() {
    $READLINK "$1"
  }

  abs_dirname() {
    local cwd="$PWD"
    local path="$1"

    while [ -n "$path" ]; do
      cd "${path%/*}"
      local name="${path##*/}"
      path="$(resolve_link "$name" || true)"
    done

    pwd
    cd "$cwd"
  }
fi

if [ -z "${GOVENV_ROOT}" ]; then
  GOVENV_ROOT="${HOME}/.govenv"
else
  GOVENV_ROOT="${GOVENV_ROOT%/}"
fi
export GOVENV_ROOT

# Pass ENV_FILE_ARG from shims to GOVENV_DIR.
if [ -z "${GOVENV_DIR}" ]; then
  if [ -n "${GOVENV_FILE_ARG}" ]; then
    if [ -L "${GOVENV_FILE_ARG}" ]; then
      GOVENV_DIR="$(abs_dirname "${GOVENV_FILE_ARG}")"
    else
      GOVENV_DIR="${GOVENV_FILE_ARG%/*}"
    fi
    export GOVENV_DIR
    unset GOVENV_FILE_ARG
  fi
fi

if [ -z "${GOVENV_DIR}" ]; then
  GOVENV_DIR="$PWD"
else
  cd "$GOVENV_DIR" 2>/dev/null || abort "cannot change working directory to \`$GOVENV_DIR'"
  GOVENV_DIR="$PWD"
  cd "$OLDPWD"
fi
export GOVENV_DIR


shopt -s nullglob

bin_path="$(abs_dirname "$0")"
for plugin_bin in "${GOVENV_ROOT}/plugins/"*/bin; do
  PATH="${plugin_bin}:${PATH}"
done
export PATH="${bin_path}:${PATH}"

GOVENV_HOOK_PATH="${GOVENV_HOOK_PATH}:${GOVENV_ROOT}/govenv.d"
if [ "${bin_path%/*}" != "$GOVENV_ROOT" ]; then
  # Add govenv's own `govenv.d` unless govenv was cloned to GOVENV_ROOT
  GOVENV_HOOK_PATH="${GOVENV_HOOK_PATH}:${bin_path%/*}/govenv.d"
fi
GOVENV_HOOK_PATH="${GOVENV_HOOK_PATH}:/usr/local/etc/govenv.d:/etc/govenv.d:/usr/lib/govenv/hooks"
for plugin_hook in "${GOVENV_ROOT}/plugins/"*/etc/govenv.d; do
  GOVENV_HOOK_PATH="${GOVENV_HOOK_PATH}:${plugin_hook}"
done
GOVENV_HOOK_PATH="${GOVENV_HOOK_PATH#:}"
export GOVENV_HOOK_PATH

shopt -u nullglob


command="$1"
case "$command" in
"" )
  { govenv---version
    govenv-help
  } | abort
  ;;
-v | --version )
  exec govenv---version
  ;;
-h | --help )
  exec govenv-help
  ;;
* )
  command_path="$(command -v "govenv-$command" || true)"
  [ -n "$command_path" ] || abort "no such command \`$command'"

  shift 1
  if [ "$1" = --help ]; then
    exec govenv-help "$command"
  else
    exec "$command_path" "$@"
  fi
  ;;
esac
