#!/usr/bin/env bash
#
# Summary: Display the full path to an executable
#
# Usage: govenv which <command>
#
# Displays the full path to the executable that govenv will invoke when
# you run the given command.

set -e
[ -n "$GOVENV_DEBUG" ] && set -x

# Provide govenv completions
if [ "$1" = "--complete" ]; then
  exec govenv-shims --short
fi

remove_from_path() {
  local path_to_remove="$1"
  local path_before
  local result=":$PATH:"
  while [ "$path_before" != "$result" ]; do
    path_before="$result"
    result="${result//:$path_to_remove:/:}"
  done
  result="${result%:}"
  echo "${result#:}"
}

GOVENV_COMMAND="$1"

if [ -z "$GOVENV_COMMAND" ]; then
  govenv-help --usage which >&2
  exit 1
fi

OLDIFS="$IFS"
IFS=: versions=(${GOVENV_VERSION:-$(govenv-version-name)})
IFS="$OLDIFS"

for version in "${versions[@]}"; do
  if [ "$version" = "system" ]; then
    PATH="$(remove_from_path "${GOVENV_ROOT}/shims")"
    GOVENV_COMMAND_PATH="$(command -v "$GOVENV_COMMAND" || true)"
  else
    GOVENV_GO_ROOT=$(govenv goroot)
    GOVENV_COMMAND_PATH="${GOVENV_GO_ROOT}/bin/${GOVENV_COMMAND}"
  fi
  if [ -x "$GOVENV_COMMAND_PATH" ]; then
    break
  fi
done

OLDIFS="$IFS"
IFS=$'\n' scripts=(`govenv-hooks which`)
IFS="$OLDIFS"
for script in "${scripts[@]}"; do
  source "$script"
done

if [ -x "$GOVENV_COMMAND_PATH" ]; then
  echo "$GOVENV_COMMAND_PATH"
elif [ "$GOVENV_VERSION" != "system" ] && [ ! -d "${GOVENV_ROOT}/versions/${GOVENV_VERSION}" ]; then
  echo "govenv: version \`$GOVENV_VERSION' is not installed (set by $(govenv-version-origin))" >&2
  exit 1
else
  any_not_installed=0
  for version in "${versions[@]}"; do
    if [ "$version" = "system" ]; then
      continue
    fi
    if ! [ -d "${GOVENV_ROOT}/versions/${version}" ]; then
      echo "govenv: version \`$version' is not installed" >&2
      any_not_installed=1
    fi
  done
  if [ "$any_not_installed" = 1 ]; then
    exit 1
  fi

  echo "govenv: $GOVENV_COMMAND: command not found" >&2

  versions="$(govenv-whence "$GOVENV_COMMAND" || true)"
  if [ -n "$versions" ]; then
    { echo
      echo "The \`$1' command exists in these Go versions:"
      echo "$versions" | sed 's/^/  /g'
      echo
    } >&2
  fi

  exit 127
fi
